### ISSUE TITLE
Custom dialog font

### ISSUE THREAD

**Issue by SlowhandFastfeet** [rotators/foclassic#32]
- I want to be able to use different font in the dialog screen than the default. 
- Need additional info about how the engine uses fonts currently, maybe there could be some workarounds for it, before someone solves this. Basically: Dialog fonts shall be different from the font that is used everywhere else, like: character nameplates, damage numbers, etc.
- Any solution is good at this point, even info about how to work around it.

**Comment by wipe2238** [comment]
This could be as easy as adding new font type - Client looks for fonts/Dialog.fnt and if it's not found, Default.fnt is loaded instead. Not a greatest solution, as it needs messing with files, but it needs minimal changes to interface code itself then.

**Comment by SlowhandFastfeet** [comment]
Agreed. Do it pls.
