### ISSUE TITLE
Return connections instead of players in ping reply

### ISSUE THREAD

**Issue by wipe2238** [rotators/foclassic#4]
Returning player count leads to making whole statistics pointless on servers using IsNoLogOut maps

**Comment by Brightside56** [comment]
I'd like to see this as separate binary/patch for r412. Also it would great to return something like nologout=1 in patched version

**Comment by wipe2238** [comment]
But... why? It's honestly easier for servers to migrate and get it out of the box, than for us to maintain two versions. r412 and FOClassic are more and more different code-wise with each day passing, and we didn't even started to work on things visible "outside".

I have some ideas about extending ping reply, but it's not mature enough to post. For sure there will be dead simple way to know if server is running FOnline or FOClassic, so status checkers will know (if they care about it) what kind of numbers they get - players or connections.
`bool IsFOClassic = (ping_response[3] > 0)`

**Comment by Brightside56** [comment]
I would like to make all servers to use this ASAP. Same as some bugfix stuff. But anyone will not use it right now because you're planning to release it incompatible with current worldsaves. That's why. Servers like Reloaded or FO2 can run its current sessions for years
