### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by wipe2238** [rotators/foclassic#9]
- [x] Binaries repository
  **UGH**. I really can't decide on this one. This one is most important, and due to that...
  On one hand, i'd love to have it as part of _SVN@FOdev_. There's gazillion reason for that, and only real limit is our free time and laziness. I could write at book how it's better solution for everyone. But...
  On the other, we didn't pick _nuremberg_ as development machine. It's neither _paris_ or _berlin_ - any of them would be 300% better for this task. FOdev, in current state, isn't _good enough_ platform, mostly due to small disk. Caps could solve that, sure, but that ain't smart move when we don't even know if project as a whole will be important/popular enough to justify that. In the end, final decision is up to ~~@lisac2k~~ @ghost2238 (you people never tell me anything!1) and discussion should take place on IRC.
  Let's get back on track - what we need from external SVN hosting:
  * binaries-friendly - not all hosters like them
  * sane download speed - no more 10KB/s please
  * ability to export whole repo, so we can move it to our machine - IF there ever will be need for that
  If anyone will say xp-dev, i'll slap him right into 2008 and leave there to fix town_control.fos
- [x] Dev dropout
  Don't think i explained it anywhere yet, sooo: a place where we can drop some random, temporary stuff; kustoms with one small thing changed to help track nasty bug, random snippets, and so on. To keep it clean, any file will be deleted shortly after last modification date - 2 weeks, month, something like that.
- [x] Discord
  Servers betrayed roots of FOnline and abandoned IRC. The nerves of those people. _Shakes fist_.
  Today every server and its dog have at least one discord guild. Asking devs to come to IRC after such a long break would be funny, but counter-productive. I have a dream! about server devs sitting in one discord channel, a central point for chit-chat about NpcPlanes and Entires. Cursing yours truly for rejecting that one specific feature they **NEED** in their life. Maybe even newcomers seeking advice about implementing new shiny stuff we added.
- [x] Forum
 This one is just a question, and will be complete regardless of what will be decided.
  Do we really need forum? I assume everyone interested in project should at least know how to use GitHub, and if not - it's about damn time, really.
  We can still use forum only for announcements, after reaching bigger milestone, anything other has to happen here. Discord will greatly filter out random questions i believe. Some will use existing boards. But we'll keep directing theme **here** and -hopefully- they will, if only to make us shut up about it :D

**Comment by BartAdv** [comment]
There are releases available on github, so binaries are gonna be on github.

**Comment by wipe2238** [comment]
Discord is prepared, more or less. Still needs some general info, links, etc.

**Comment by wipe2238** [comment]
Dropout cleanup solved by single line in crontab :>
Currently commented, as it might collide with project page setup. Once #5 is finished and directory is set properly, it should work just fine.

**Comment by wipe2238** [comment]
No word about forum anywhere for 2 weeks, sssooo...

Forum will be for announcements only, most likely progress reports after finishing major milestones... and that's it. Any "_how do i thing_?" threads which might show up, have to live next to FOnline-related ones in already existing boards.

Howgh.
